In [1]:
import numpy as np
import pandas as pd

from chh_swpt_calibration import swaption, swpt_calibration, term_structure

In [2]:
t = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 12, 15, 20, 25, 30])
m = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 15, 20, 25, 30])
yield_source = np.array([4.890, 4.555, 4.164, 3.923, 3.778, 3.684, 3.616, 3.570, 3.542, 3.527, 3.519, 3.515, 3.425, 3.327, 3.204]) / 100
y = term_structure.YieldCurve(t, yield_source)
p = y.to_discount_curve()

In [3]:
fwd_swap = pd.read_csv("forward_swap.csv", index_col=0)
swpt_quote = pd.read_csv("swaption_quote.csv", index_col=0)
swpt_quote

1Yr    2Yr    3Yr    4Yr    5Yr    6Yr    7Yr    8Yr    9Yr   10Yr  \
1Yr   32.05  35.15  37.94  36.43  37.26  35.80  36.48  33.82  33.23  33.90   
2Yr   41.25  40.21  40.28  38.68  37.17  35.29  35.93  33.23  27.89  32.15   
3Yr   39.89  40.02  36.49  37.19  34.73  33.48  31.93  30.70  30.24  31.25   
4Yr   39.64  37.24  35.46  35.17  35.14  30.91  30.24  28.90  28.00  28.06   
5Yr   35.84  34.00  33.09  31.21  29.78  28.53  28.54  27.26  26.59  25.99   
6Yr   30.48  30.03  29.87  28.46  27.17  25.90  25.42  24.84  24.01  23.88   
7Yr   30.13  40.63  39.88  34.14  28.71  25.23  26.78  24.08  23.79  23.60   
8Yr   26.02  25.36  24.92  24.16  23.47  22.99  22.55  22.38  22.24  22.12   
9Yr   23.72  23.56  23.50  22.72  21.97  21.50  21.57  21.52  21.49  21.49   
10Yr  25.06  23.80  22.94  23.12  22.55  21.59  21.81  21.30  21.17  20.88   
15Yr  22.00  21.33  20.77  20.63  20.31  20.35  20.34  20.05  20.51  21.54   
20Yr  22.85  21.68  21.65  21.62  21.53  21.56  21.57  22.50  22.49  24.90   
25Yr  25.31  24.20  22.75  22.55  25.72  22.46  23.22  24.07  24.45  24.32   
30Yr  25.70  24.66  24.95  25.64  26.55  26.33  26.40  27.05  27.84  28.58   

       12Yr   15Yr   20Yr   25Yr   30Yr  
1Yr   33.22  32.26  31.57  29.99  30.13  
2Yr   31.25  30.06  28.35  28.47  28.71  
3Yr   30.36  29.21  26.54  26.02  26.20  
4Yr   26.84  25.09  25.06  25.39  25.42  
5Yr   25.37  24.40  23.79  24.20  24.37  
6Yr   23.65  23.34  23.28  24.00  24.86  
7Yr   23.22  22.76  22.25  22.55  23.46  
8Yr   21.99  21.98  22.30  22.79  23.71  
9Yr   21.44  21.40  21.95  22.30  23.44  
10Yr  20.92  20.87  21.15  20.78  22.02  
15Yr  21.05  20.19  21.11  21.66  21.25  
20Yr  23.93  22.29  21.49  24.97  22.63  
25Yr  24.85  25.54  28.19  27.77  26.86  
30Yr  30.34  32.67  32.13  29.29  17.02

In [4]:
fwd_swap

1Yr     2Yr     3Yr     4Yr     5Yr     6Yr     7Yr     8Yr     9Yr  \
1Yr   4.5322  3.4379  3.2481  3.2480  3.3124  3.1862  3.3094  3.3930  3.5304   
2Yr   2.9032  3.3439  3.2482  3.2796  3.2502  3.2469  3.3505  3.4604  3.5717   
3Yr   3.6905  3.3129  3.2688  3.2486  3.2694  3.2940  3.4085  3.5073  3.5293   
4Yr   3.5851  3.3128  3.2493  3.2639  3.2988  3.3503  3.4555  3.4911  3.5396   
5Yr   3.5338  3.2890  3.2607  3.2881  3.3423  3.3983  3.4524  3.5063  3.5476   
6Yr   3.4801  3.2921  3.2813  3.3256  3.3828  3.4046  3.4709  3.5180  3.5514   
7Yr   3.4579  3.3052  3.3137  3.3631  3.3902  3.4263  3.4853  3.5250  3.5208   
8Yr   3.4506  3.3304  3.3473  3.3717  3.4105  3.4436  3.4950  3.5018  3.4979   
9Yr   3.4584  3.3574  3.3564  3.3913  3.4272  3.4562  3.4776  3.4827  3.4809   
10Yr  3.4711  3.3645  3.3751  3.4077  3.4397  3.4441  3.4628  3.4690  3.4666   
15Yr  3.4787  3.3957  3.3897  3.3977  3.4047  3.3681  3.3417  3.3031  3.2570   
20Yr  3.4196  3.3253  3.2907  3.2669  3.2413  3.2020  3.1697  3.1274  3.0795   
25Yr  3.2899  3.2013  3.1635  3.1348  3.1042  3.0554  3.0118  2.9599  2.9024   
30Yr  3.1674  3.0766  3.0307  2.9922  2.9515  2.9069  2.8674  2.9206  2.7688   

        10Yr    12Yr    15Yr    20Yr    25Yr    30Yr  
1Yr   3.6053  3.5725  3.3155  2.5800  2.3374  1.8430  
2Yr   3.5237  3.5774  3.3156  2.5836  2.3343  1.8429  
3Yr   3.5394  3.5758  3.3186  2.5824  2.3311  1.8430  
4Yr   3.5486  3.5139  3.3179  2.5818  2.3311  1.8442  
5Yr   3.5539  3.4749  3.3175  2.5811  2.3323  1.8440  
6Yr   3.5174  3.4517  3.2024  2.5429  2.2549  1.8438  
7Yr   3.4900  3.4340  3.1215  2.5146  2.1989  1.8437  
8Yr   3.4715  3.4208  3.0599  2.4934  2.1573  1.8442  
9Yr   3.4563  3.3374  3.0119  2.4769  2.1252  1.8435  
10Yr  3.4441  3.2718  2.9736  2.4639  2.0991  1.8435  
15Yr  4.1959  3.0431  2.7849  2.2768  2.0205  1.7238  
20Yr  3.0190  2.8556  2.5849  2.1824  1.8944  1.6645  
25Yr  2.8337  2.6933  2.4632  2.0588  1.8189  1.6289  
30Yr  2.7075  2.5632  2.3287  1.9759  1.7684  1.6051

In [5]:
price_grid = np.zeros(fwd_swap.shape)
for i in range(len(price_grid)):
    for j in range(len(price_grid[i])):
        s = swpt_quote.iloc[i, j] / 100
        f = fwd_swap.iloc[i, j] / 100
        swpt = swaption.Swaption(f, m[i], t[j], s, f, p)
        price_grid[i][j] = swpt.price
price_grid

array([[0.00549483, 0.00456731, 0.00465373, 0.00447046, 0.00466179,
        0.00431037, 0.00456115, 0.00433875, 0.00443642, 0.00462103,
        0.00448799, 0.00404582, 0.00308153, 0.00265312, 0.00210163],
       [0.00608189, 0.00683326, 0.00664895, 0.00645328, 0.00615157,
        0.00584108, 0.00613445, 0.00586862, 0.00509773, 0.00578513,
        0.00571157, 0.00509509, 0.00374747, 0.0034    , 0.00270658],
       [0.00880234, 0.00792645, 0.00715485, 0.00724243, 0.00682155,
        0.00663249, 0.00655352, 0.00648989, 0.00643498, 0.00666381,
        0.00654505, 0.00584915, 0.00414317, 0.00366795, 0.00291966],
       [0.00944431, 0.00822337, 0.00769651, 0.00767044, 0.00774611,
        0.00695187, 0.00701947, 0.00678639, 0.00667202, 0.00670295,
        0.00635584, 0.00561846, 0.00436684, 0.00399363, 0.00316313],
       [0.00910896, 0.00806382, 0.00779018, 0.00742769, 0.00721709,
        0.00704053, 0.00715504, 0.00695104, 0.00686516, 0.00672653,
        0.00642432, 0.0059047 , 0.00448187, 

In [6]:
chh_calib = swpt_calibration.ChhCalibration(price_grid, p)

In [7]:
chh_calib.v

array([[0.0144639 , 0.01246622, 0.01319769, 0.01307874, 0.01423293,
        0.0134754 , 0.01500518, 0.01468062, 0.01576122, 0.01748092,
        0.01874061, 0.01925811, 0.015834  , 0.01579935, 0.        ],
       [0.01600921, 0.01885448, 0.01898367, 0.01902767, 0.01868754,
        0.01826129, 0.02013636, 0.01984572, 0.01720293, 0.02165356,
        0.02406188, 0.02414157, 0.01772914, 0.        , 0.        ],
       [0.02317047, 0.02171843, 0.02017994, 0.02119019, 0.0205257 ,
        0.02062306, 0.02113404, 0.02176115, 0.02256498, 0.02532418,
        0.02807554, 0.0281014 , 0.        , 0.        , 0.        ],
       [0.02486042, 0.02250512, 0.0217377 , 0.02243596, 0.02352848,
        0.0215073 , 0.02262932, 0.02257964, 0.02315361, 0.02485833,
        0.02581873, 0.        , 0.        , 0.        , 0.        ],
       [0.02397761, 0.02208141, 0.02206458, 0.02168537, 0.02176443,
        0.02194247, 0.02337782, 0.02360733, 0.02456798, 0.02533959,
        0.        , 0.        , 0.        , 

In [10]:
chh_calib.xi

array([[ 1.44638957e-02, -1.99767275e-03,  7.31471347e-04,
        -1.18951242e-04,  1.15418490e-03, -7.57523115e-04,
         1.52977974e-03, -3.24560504e-04,  1.08059578e-03,
         1.71970060e-03,  1.25968593e-03,  5.17505639e-04,
        -3.42410800e-03, -3.46490812e-05,  0.00000000e+00],
       [ 1.58840868e-02,  2.92783155e-03,  1.21154145e-04,
         9.31976344e-05, -3.64895477e-04, -4.08111679e-04,
         1.88192854e-03, -3.31916349e-04, -2.86697390e-03,
         4.29072230e-03,  2.35240527e-03,  5.23226310e-04,
        -6.42388567e-03,  0.00000000e+00,  0.00000000e+00],
       [ 2.29731002e-02, -1.47848300e-03, -1.63925026e-03,
         1.12777425e-03, -7.53334834e-04, -1.71513485e-04,
         4.46109647e-04,  6.44911219e-04, -1.43043123e-04,
         2.14467414e-03,  3.48266366e-03,  1.21164742e-03,
         0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
       [ 2.48158383e-02, -2.55280616e-03, -6.18912720e-04,
         5.42984674e-04,  1.07537850e-03, -2.07486841